### ISSUE TITLE
Windows

### ISSUE THREAD

**Issue by plicease** [PerlFFI/FFI-ExtractSymbols#1]
Probably a red herring, appears to be freeware but no source
http://www.dependencywalker.com/

**Comment by plicease** [comment]
http://www.codeguru.com/cpp/v-s/debug/article.php/c1269/LibDump-Tool.htm

**Comment by plicease** [comment]
https://social.msdn.microsoft.com/forums/windowsdesktop/en-us/ab3cd884-fcb3-442a-9798-62d9ed31c1cb/list-of-exported-functions-of-a-dll

**Comment by plicease** [comment]
http://www.autoitscript.com/forum/topic/118467-list-function-names-from-dll-file/

**Comment by plicease** [comment]
We now have a dumpbin implementation, so that covers MSVC++

ec105446b3bc94e8860a95075eee9a31e5684bd9

it also works for cygwin or strawberry if you set FFI_EXTRACTSYMBOLS_DUMPBIN to the path of dumpbin assuming you have MSVC++

Thing I noticed when working on this.  Although nm and objdump do not work with many of the DLLs that come from cygwin or strawberry, they do seem to work with the DLL generated from libtest.

```
xian-x86_64% objdump -t cygtest-1.dll|grep my
[ 23](sec  1)(fl 0x00)(ty  20)(scl   2) (nx 1) 0x0000000000000080 my_function
[305](sec -2)(fl 0x00)(ty   0)(scl 103) (nx 1) 0x0000000000000159 pseudo-reloc-dummy.c
[504](sec  7)(fl 0x00)(ty   0)(scl   2) (nx 0) 0x00000000000001b0 my_variable
```

```
xian-x86_64% nm -P -g cygtest-1.dll|grep my
my_function T 0000000528101080
my_variable B 00000005281071b0
```

```
```

**Comment by plicease** [comment]
http://www.codeproject.com/Tips/133747/Checking-for-exported-symbols-functions-in-a-DLL-w

**Comment by sanko** [comment]
I really didn't want to install Visual Studio just for `dumpbin.exe` so, if you're interested in a pure perl solution, I wrote a [module to extract exports](https://metacpan.org/module/App::dumpbin/source) from both 32bit and 64bit DLLs.

**Comment by plicease** [comment]
@sanko how would you feel about incorporating that code directly into FFI::ExtractSymbols::Windows?

**Comment by sanko** [comment]
That would be ideal; submitting a PR to do so was my eventual goal after broader testing. You're more than welcome to just copy and paste it in yourself or I can have a pull request ready by the weekend.

Edit: Besides adding 64bit support, the PE/COFF specification around our use case has gone unchanged since 1993 so it should be considered more than stable but I am more than willing to keep an eye out for any edge cases that pop up (non-standard/broken compilers doing wonky things, etc.).

**Comment by plicease** [comment]
@sanko I'd appreciate a PR when you are ready.

**Comment by plicease** [comment]
@sanko If you can add the first commit from https://github.com/PerlFFI/FFI-ExtractSymbols/pull/12 into your PR that would verify that it works on Strawberry, MinGW and Cygwin.  The second commit just adds `App::dumpbin` as a prereq to verify that it should pass. 

I'm debating it, but I think the old code that relies on dumpbin.exe should be removed entirely, as I agree the executable format is quite stable and is unlikely to change again.
