### ISSUE TITLE
nm does not work with stripped dynamic libraries

### ISSUE THREAD

**Issue by plicease** [PerlFFI/FFI-ExtractSymbols#3]
http://stackoverflow.com/questions/9961473/nm-vs-readelf-s

This is related to #1 in that the reason I thought that I can't use `nm` on windows is actually because I can't use `nm` on stripped binaries (I just happened to be testing cygwin and strawberry .dll files which had been stripped).  `readelf` works for platforms that have `readelf` which include Linux and cygwin, and that use ELF format which DOES NOT include cygwin :P

**Comment by plicease** [comment]
This provides the information that I need

`objdump -x /usr/bin/cygarchive-13.dll`

but a whole lot extra.  Would be good if we could narrow it down.

**Comment by plicease** [comment]
`-p` narrows it down a little.

**Comment by sanko** [comment]
I've been monkey patching `FFI::ExtractSymbols::PosixNm` with this around line 51:

      foreach my $line (`$nm -g -P -D $libpath`)

...to get dynamic symbols from stripped libs in a little project I'm tinkering on today but it would be nice to eventually be able to release what I'm working on to CPAN.

**Comment by plicease** [comment]
@sanko that would be a good PR.  The one thing that we want to watch out for is the portability of the new flag.  If older versions of nm or different platforms do not support it we have to not use it on those platforms.

**Comment by sanko** [comment]
Yep, testing is exactly why I haven't forked or done anything else in prep for a PR yet. Woke up this morning with the idea to wrap SDL2 with FFI::Platypus to create a microui clone and this is where I stopped a half hour in. :) I don't mind digging into it further but it's been in the GNU version of `nm` since [1994](https://sourceware.org/git/?p=binutils-gdb.git;a=commitdiff;h=8291be48a9ca4209b5d200f7d42610a3a86f5cc7).

**Comment by plicease** [comment]
> Yep, testing is exactly why I haven't forked or done anything else in prep for a PR yet. Woke up this morning with the idea to wrap SDL2 with FFI::Platypus to create a microui clone and this is where I stopped a half hour in. :) I don't mind digging into it further but it's been in the GNU version of `nm` since [1994](https://sourceware.org/git/?p=binutils-gdb.git;a=commitdiff;h=8291be48a9ca4209b5d200f7d42610a3a86f5cc7).

Yeah seems safe for Linux, I just want to make sure that it still works on say FreeBSD and NetBSD (looks like OpenBSD is special and uses a totally different class).   Given a PR I can test on VMs for these systems if you don't have access to those arch.

**Comment by sanko** [comment]
Was cleaning up my desktop and rediscovered my old SDL2 project. Life comes at you fast but has there been any further testing on my meager, 3 character, pull request at #7? :) I don't have any BSD boxes to test on. (Today, I synced my fork with your commits from March so, after testing, it should merge cleanly as it's passing github's checks again.)

**Comment by plicease** [comment]
@sanko I will endeavor to try this out on some BSDs in the near future.  I’ve assigned the PR to myself to review which should keep it on my radar, but if nothing has happened in a couple of weeks please feel free to bump this.

**Comment by plicease** [comment]
Should be fixed in 0.05
